export const projects = [
  {
    title: 'React Music Listening App',
    description: "A Music Listening App like Spotify in a versatile design.Has All the Features Such a Music Player,Search Option,Top Charts,Top Artists,Artist Page,Song Details Page with Lyrics and related Songs,Around You Page,etc",
      image: '/images/1.png',
      tags: ['React', 'Redux', 'Shazam Core API', 'Tailwind'],
    source: 'https://github.com/Govi2020/Spotify-Clone',
    visit: 'https://music-lyriks.vercel.app/',
    id: 0,
  },
  {
    title: 'Social Media App',
    description:"A Full Stack Social Media like Twitter and Facebook,With all the bare bone features of a social media app like liking posts,following people,auth system,chatting with people,creating post,commenting post,searching etc",
    image: '/images/2.png',
    tags: ['React', 'Firebase Storage',"Mongo DB","Express js","Socket"],
    source: 'https://github.com/Govi2020/Social-Media-App',
    visit: 'https://govi-social.netlify.app/',
    id: 1,
  },
  {
    title: 'SunnySide Landing Page',
    description: "A Front end mentor Challenge Completed.Mobile Responsive like all of the others",
      image: '/images/3.png',
      tags: ['HTML', 'CSS',"JS"],
    source: 'https://github.com/Govi2020/SunnySide-Landing-Page',
    visit: 'https://frabjous-cat-e3c1ea.netlify.app/',
    id: 2,
  },
  {
    title: 'Blog Website',
    description: "A Blog Website Where You Can Create Your Own Blog,See Other Blog,With a Custom Text Editor,Edit The Posts and more.But didn't made it responsive",
    image: '/images/4.png',
    tags: ['React', 'Node', 'Express',"mySQL"],
    source: 'https://github.com/Govi2020/Blog-Creater-Website',
    visit: 'https://blog-creater-website-production.up.railway.app/',
    id: 3,
  },
  {
    title: 'IP Tracker',
    description: "Front End Mentor Challenge Completed.You Can See Your Own IP Address and location and you can see other's too",
    image: '/images/5.png',
    tags: ['React', 'Leaflet','API'],
    source: 'https://github.com/Govi2020/IP-Tracker',
    visit: 'https://ip-tracker-chi.vercel.app/',
    id: 4,
  },
  {
    title: 'URL Shortener',
    description: "Front End Mentor Challenge Completed.You Can See Shorten Your Links",
    image: '/images/6.png',
    tags: ['Svelte', "API"],
    source: 'https://github.com/Govi2020/G-Shortly',
    visit: 'https://g-shortly.netlify.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2019, text: 'Learned Unity Game Engine', },
  { year: 2020, text: 'Learned Full Stack Development', },
  { year: 2021, text: 'Learned Cyber Security', },
  { year: 2022, text: 'Learned Machine Learning', },
  { year: 2022, text: 'Started A Blog in HashNode', },
  { year: 2023, text: 'Worked as a freelance developer and Exploring More', },
];
